"""
Generate realistic synthetic CGM data in the FreeStyle Libre CSV export format
and a matching JSON file. Produces ~21 days of 15-min-interval readings with
diurnal patterns, post-meal spikes, dawn phenomenon, noise, and a few
intentional "interesting" days to exercise the recommendation engine.

Run:
    python scripts/generate_sample_data.py
Outputs:
    sample_data/libre_export_sample.csv
    sample_data/libre_export_sample.json
"""
from __future__ import annotations

import csv
import json
import math
import os
import random
from datetime import datetime, timedelta

random.seed(42)

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "sample_data")
CSV_PATH = os.path.abspath(os.path.join(OUT_DIR, "libre_export_sample.csv"))
JSON_PATH = os.path.abspath(os.path.join(OUT_DIR, "libre_export_sample.json"))

DAYS = 21
INTERVAL_MIN = 15  # Libre historic readings
SERIAL = "1A2B3C4D"
DEVICE = "FreeStyle LibreLink"


def simulate_day(base_date: datetime, day_index: int) -> list[tuple[datetime, float]]:
    """Simulate one day of glucose readings with diurnal patterns and meals."""
    readings: list[tuple[datetime, float]] = []

    # Day-to-day baseline drift. Make the last few days gradually rise to trigger the trend rule.
    if day_index < 10:
        baseline = 130 + random.uniform(-10, 10)
    elif day_index < 16:
        baseline = 140 + random.uniform(-5, 10)
    else:
        baseline = 155 + day_index * 1.5 + random.uniform(-5, 10)

    # Day 7: a "high variability" day
    high_var_day = (day_index == 7)
    # Day 12: a low-coverage day (sensor gap)
    low_coverage_day = (day_index == 12)
    # Day 15: a low-glucose excursion day
    low_day = (day_index == 15)

    # Meal times (hour, carb impact magnitude)
    meals = [(7.5, 55), (12.5, 70), (18.5, 80)]

    slots = int(24 * 60 / INTERVAL_MIN)
    for i in range(slots):
        ts = base_date + timedelta(minutes=i * INTERVAL_MIN)
        hour = ts.hour + ts.minute / 60.0

        # Diurnal circadian component
        circ = 10 * math.sin((hour - 6) / 24 * 2 * math.pi)

        # Dawn phenomenon (3am-7am rise)
        dawn = 0
        if 3 <= hour <= 7:
            dawn = 15 * math.sin((hour - 3) / 4 * math.pi)

        # Meal spikes (centered ~1h after meal)
        meal_effect = 0
        for mh, mag in meals:
            dt = hour - (mh + 1.0)
            meal_effect += mag * math.exp(-(dt ** 2) / 1.5)

        noise = random.gauss(0, 6 if not high_var_day else 22)
        value = baseline + circ + dawn + meal_effect + noise

        if low_day and 14 <= hour <= 16:
            value -= 70  # drop into lows
        if high_var_day:
            value += random.choice([-25, 0, 25])

        value = max(45, min(340, value))

        if low_coverage_day and random.random() < 0.7:
            continue  # simulate sensor gap

        readings.append((ts, round(value, 1)))

    return readings


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    start = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0) - timedelta(days=DAYS)

    all_readings: list[tuple[datetime, float]] = []
    for d in range(DAYS):
        day_start = start + timedelta(days=d)
        all_readings.extend(simulate_day(day_start, d))

    # --- Write Libre-style CSV ---
    # Libre exports have two metadata rows before the header.
    with open(CSV_PATH, "w", newline="") as f:
        f.write(f"Glucose Data,Generated by sample generator,{datetime.now().isoformat()}\n")
        f.write(f"Device,{DEVICE},Serial Number,{SERIAL}\n")
        writer = csv.writer(f)
        writer.writerow([
            "Device", "Serial Number", "Device Timestamp", "Record Type",
            "Historic Glucose mg/dL", "Scan Glucose mg/dL",
            "Non-numeric Rapid-Acting Insulin", "Rapid-Acting Insulin (units)",
            "Non-numeric Food", "Carbohydrates (grams)",
        ])
        for ts, val in all_readings:
            writer.writerow([
                DEVICE, SERIAL, ts.strftime("%m-%d-%Y %H:%M"),
                "0", f"{val:.0f}", "", "", "", "", "",
            ])

    # --- Write JSON ---
    json_data = {
        "device": DEVICE,
        "serial_number": SERIAL,
        "exported_at": datetime.now().isoformat(),
        "readings": [
            {
                "timestamp": ts.isoformat(),
                "glucose_mgdl": val,
                "record_type": "historic",
            }
            for ts, val in all_readings
        ],
    }
    with open(JSON_PATH, "w") as f:
        json.dump(json_data, f, indent=2)

    print(f"Wrote {len(all_readings)} readings")
    print(f"  CSV:  {CSV_PATH}")
    print(f"  JSON: {JSON_PATH}")


if __name__ == "__main__":
    main()
